name: Daily Run For OrangeHRM

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore "{{ github.workspace }}/OrangeHRMLive/OrangeHRMLive.csproj"

      - name: Build
        run: dotnet build "{{ github.workspace }}/OrangeHRMLive/OrangeHRMLive.csproj" --configuration Release --no-restore

      - name: Run the tests
        run: dotnet test "{{ github.workspace }}/OrangeHRMLive/OrangeHRMLive.csproj" --no-build --verbosity normal
      
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test-Results
          path: /home/runner/work/OrangeHRMLive/OrangeHRMLive/OrangeHRMLive/bin/Release/net8.0/TestResults/**
