name: Hourly Run For OrangeHRM

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Run Selenium Tests
      run: dotnet test --logger "trx;LogFileName=test_results.trx"

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: /home/runner/work/OrangeHRMLive/OrangeHRMLive/OrangeHRMLive/TestResults/test_results.trx
        
    - name: Convert .trx to HTML (Optional step to make results more readable)
      if: always()
      run: |
        dotnet tool install --global trx2html
        trx2html /home/runner/work/OrangeHRMLive/OrangeHRMLive/OrangeHRMLive/TestResults/test_results.trx -o /home/runner/work/OrangeHRMLive/OrangeHRMLive/OrangeHRMLive/TestResults/test_results.html

    - name: Upload HTML Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-html
        path: /home/runner/work/OrangeHRMLive/OrangeHRMLive/OrangeHRMLive/TestResults/test_results.html  # Correct path
