name: Hourly Run For OrangeHRM

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Ensure this matches your project’s .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run the tests
        run: dotnet test --logger:trx --results-directory /home/runner/work/OrangeHRMLive/OrangeHRMLive/OrangeHRMLive/TestResults

      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Test-Results
          path: /home/runner/work/OrangeHRMLive/OrangeHRMLive/OrangeHRMLive/TestResults  # This folder contains the reports, screenshots, etc.

  upload-artifacts:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Upload all test output as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-output
          path: /home/runner/work/OrangeHRMLive/OrangeHRMLive/OrangeHRMLive/TestResults/Reports   # Replace with the correct path to your output folder
          retention-days: 5  # Optionally set how many days the artifact is stored
